:: This installs .NET via WinGet. Only supported on Windows 10 and higher.
@echo off
echo Installing .NET 6 SDK...
winget install Microsoft.DotNet.SDK.6
echo Installing .NET 7 SDK...
winget install Microsoft.DotNet.SDK.7
echo Installing .NET 8 SDK...
winget install Microsoft.DotNet.SDK.8
echo Installing .NET 9 SDK...
winget install Microsoft.DotNet.SDK.Preview